"""配置常量。"""

BACKUP_ROOT_NAME = "BACKUP"
ENCRYPTED_DIRNAME = "ENCRYPTED"
INDEX_DIRNAME = "_INDEX"
DB_FILENAME = "BACKUP_STATE.db"
CHECKSUM_DIRNAME = "_CHECKSUM"
PAR2_DIRNAME = "_PAR2"

ARCHIVE_NAME_PATTERN = "{yyyy}-{mm:02d}__{source_type}__{job_id}.7z"

DEFAULT_SOURCE_TYPES = ["相机", "屏幕录制", "手机", "下载", "Insta360", "其他"]

TIME_BASIS_MTIME = "mtime"
TIME_BASIS_CTIME = "ctime"
TIME_BASIS_EXIF = "exif"

MODE_PLAIN = "plain"
MODE_MOVE = "move"
MODE_ENCRYPTED = "encrypted"

SHA256_EXT = ".sha256"

CHUNK_SIZE = 1024 * 1024

PAR2_EXE_NAME = "par2.exe"
